version: '3.4'

services:
  ungewoehnlichesverhalten.dvp:
    ports: 
      - "8001:80"
    build:
      context: ./DVP
      dockerfile: Dockerfile
  ungewoehnlichesverhalten.as:
    ports: 
      - "8002:80"
    build:
      context: ./AnlaufstellenService
      dockerfile: Dockerfile
  ungewoehnlichesverhalten.uvereignis:
    ports: 
      - "8003:80"
    build:
      context: ./uvereignisservice
      dockerfile: Dockerfile
