version: '3.4'

services:
  db:
    image: postgres
    ports:
      - "9082:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  uve:
    ports:
    - "8082:8082"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db